### PR TITLE
Rename block statement to compound statement

### PR DESCRIPTION
**Pull request by Lai-YT**
The term "block" is a more general concept commonly associated with scopes (6.2.1), used across various expressions and statements. To provide clarity and specificity, the AST node is renamed to indicate a compound statement (6.8.2).

Several variables are renamed correspondingly.

> [!note]
> Let's follow the reference manual. :sunglasses: 

# Reference manual

## 6.8 Statements and blocks

statement:
- labeled-statement
- compound-statement
- expression-statement
- selection-statement
- iteration-statement
- jump-statement

### 6.8.2 Compound statement

compound-statement:
- { block-item-list(opt) }

block-item-list:
- block-item
- block-item-list block-item

block-item:
- declaration
- statement

### CODE REVIEW

**Review by leewei05 — APPROVED** [review]
LGTM!

**Comment by leewei05** [comment]
@Lai-YT Sorry bout that! Need to fix some conflicts with the last PR. 🙏🏼

**Comment by Lai-YT** [comment]
> @Lai-YT Sorry bout that! Need to fix some conflicts with the last PR. 🙏🏼

No problem! :ok_hand: I'll fixed them. :smile:

**Comment by Lai-YT** [comment]
Conflict fixed! :muscle:

**Pull request merged**
